#! /bin/sh

export LC_ALL=C

. $abs_top_srcdir/tests/test-lib.sh
use_local_logscan
use_tmpdir

# ==============================================================

cat > one <<EOF
xyz

def
abc

def
abc
EOF

cat > two <<EOF
abc
def

abc
def

zyx
EOF

# --------------------------------------------------------------
# Checking a single file

check 'logscan -y abc -y def -n xyz -n zyx one || echo status: $?' <<EOF
Unexpected pattern 'xyz' matches at one:1
status: 1
EOF

check 'logscan --silent -y abc -y def -n xyz -n zyx one || echo status: $?' <<EOF
status: 1
EOF

check 'logscan -y abc -y def -n xyz -n zyx two' <<EOF
EOF

check 'logscan --verbose -y abc -y def -n xyz -n zyx two' <<EOF
Pattern 'abc' matches at two:1
Pattern 'def' matches at two:2
EOF

check 'logscan -y abc -y def -n xyz -n zyx one --label=label1 || echo status: $?' <<EOF
Unexpected pattern 'xyz' matches at label1:1
status: 1
EOF

# --------------------------------------------------------------
# Checking without waiting

check 'logscan -n xxx -t 0 one || echo status: $?' <<EOF
EOF

check 'logscan -y xxx -t 0 one || echo status: $?' <<EOF
Patterns not matched:
one: 'xxx'
status: 1
EOF

# --------------------------------------------------------------
# Checking multiple files at once

check '(logscan --verbose -y abc -y def -n xyz -n zyx one two 2>&1 || echo status: $?) | sort' <<EOF
Pattern 'abc' matches at two:1
Pattern 'def' matches at two:2
Unexpected pattern 'xyz' matches at one:1
status: 1
EOF

check '(logscan --verbose -y abc -y def -n xyz -n zyx -ppos one two 2>&1 || echo status: $?) | sort' <<EOF
Pattern 'abc' matches at two:1
Pattern 'def' matches at two:2
Unexpected pattern 'xyz' matches at one:1
status: 1
EOF

check '(logscan --verbose -y abc -y def -n xyz -n zyx -ppos one two 2>&1 || echo status: $?) | sort' <<EOF
Pattern 'abc' matches at one:4
Pattern 'abc' matches at two:4
Pattern 'def' matches at one:3
Pattern 'def' matches at two:5
EOF

check '(logscan --verbose -y abc -y def -n xyz -n zyx -ppos one two 2>&1 || echo status: $?) | sort' <<EOF
Pattern 'abc' matches at one:7
Pattern 'def' matches at one:6
Unexpected pattern 'zyx' matches at two:7
status: 1
EOF

echo abc >> one
echo def >> two
check 'logscan -y abc -y def -n xyz -n zyx -ppos -t 0.1 one two || echo status: $?' <<EOF
Timeout waiting for patterns to match -- not matched:
one: 'def'
two: 'abc'
status: 1
EOF

# --------------------------------------------------------------
# Waiting for log entries

( sleep 0.1; echo abc; sleep 0.1; echo def ) >> one &

check 'logscan --verbose -y abc -y def -n xyz -n zyx -ppos -t 0.3 one' <<EOF
Pattern 'abc' matches at one:9
Pattern 'def' matches at one:10
EOF

( echo def; echo abc ) >> two

check 'logscan --verbose -y abc -y def -n xyz -n zyx -ppos two' <<EOF
Pattern 'def' matches at two:9
Pattern 'abc' matches at two:10
EOF

# ----------------------------------------------------------------
# Filter option

check 'logscan --verbose -f a -y abc one || echo status: $?' <<EOF
Pattern 'abc' matches at one:4
EOF

check 'logscan -f a -n acb one -t 0 || echo status: $?' <<EOF
EOF

# --------------------------------------------------------------
# Option parsing

check 'logscan -p pos -p pos one || echo status: $?' <<EOF
multiple conflicting -p options
Try logscan -h.
status: 2
EOF

check 'logscan -p pos one -p pos -y one || echo status: $?' <<EOF
multiple conflicting -p options
Try logscan -h.
status: 2
EOF

check 'logscan one --label one || echo status: $?' <<EOF
one: no search patterns specified
Try logscan -h.
status: 2
EOF

rm -f pos

# --------------------------------------------------------------
# Combinations of log and position tracking files and patterns

# Global options
check 'logscan --verbose -p pos -y abc one two || echo status: $?' <<EOF
Pattern 'abc' matches at one:4
Pattern 'abc' matches at two:1
EOF
check 'cat pos' <<EOF
5 13 one
2 4 two
EOF
rm -f pos

# Local options, one position tracking file
check 'logscan --verbose one -p pos -y xyz two -p pos -y zyx || echo status: $?' <<EOF
Pattern 'xyz' matches at one:1
Pattern 'zyx' matches at two:7
EOF
check 'cat pos' <<EOF
2 4 one
8 22 two
EOF
rm -f pos

# Two different position tracking files for the same log file
check 'logscan --verbose one -p pos1 -y abc one -p pos2 -y abc || echo status: $?' <<EOF
Pattern 'abc' matches at one:4
Pattern 'abc' matches at one:4
EOF
check 'cat pos1' <<EOF
5 13 one
EOF
check 'cat pos2' <<EOF
5 13 one
EOF
rm -f pos1 pos2

# Patterns for the same log file and position tracking file are merged
check 'logscan --verbose one -p pos -y abc one -p pos -y def || echo status: $?' <<EOF
Pattern 'def' matches at one:3
Pattern 'abc' matches at one:4
EOF
rm -f pos

# ----------------------------------------------------------------
# Example of matching mixed logfile entries

cat > log <<EOF
proc1: started
proc1: stopped
proc2: started
proc1: started
proc2: stopped
proc1: stopped
proc2: started
proc2: stopped
EOF

check 'logscan --verbose -y started \
	log --label log:proc1 -p pos1 -f proc1 \
	log --label log:proc2 -p pos2 -f proc2' <<EOF
Pattern 'started' matches at log:proc1:1
Pattern 'started' matches at log:proc2:3
EOF

check 'logscan --verbose -y stopped \
	log --label log:proc1 -p pos1 -f proc1 \
	log --label log:proc2 -p pos2 -f proc2' <<EOF
Pattern 'stopped' matches at log:proc1:2
Pattern 'stopped' matches at log:proc2:5
EOF

check 'logscan --verbose -y started \
	log --label log:proc1 -p pos1 -f proc1 \
	log --label log:proc2 -p pos2 -f proc2' <<EOF
Pattern 'started' matches at log:proc1:4
Pattern 'started' matches at log:proc2:7
EOF

check 'logscan --verbose -y stopped \
	log --label log:proc1 -p pos1 -f proc1 \
	log --label log:proc2 -p pos2 -f proc2' <<EOF
Pattern 'stopped' matches at log:proc1:6
Pattern 'stopped' matches at log:proc2:8
EOF
rm -f proc1 proc2
