#! /bin/sh

export LC_ALL=C

. $srcdir/test-lib.sh
use_local_logscan
use_tmpdir

# ==============================================================

cat > one <<EOF
xyz

def
abc

def
abc
EOF

cat > two <<EOF
abc
def

abc
def

zyx
EOF

# --------------------------------------------------------------
# Checking a single file

check 'logscan -y abc -y def -n xyz -n zyx one || echo status: $?' <<EOF
Unexpected pattern 'xyz' matches at one:1
status: 1
EOF

check 'logscan --silent -y abc -y def -n xyz -n zyx one || echo status: $?' <<EOF
status: 1
EOF

check 'logscan -y abc -y def -n xyz -n zyx two' <<EOF
EOF

check 'logscan --verbose -y abc -y def -n xyz -n zyx two' <<EOF
Pattern 'abc' matches at two:1
Pattern 'def' matches at two:2
EOF

check 'logscan -y abc -y def -n xyz -n zyx label1:one || echo status: $?' <<EOF
Unexpected pattern 'xyz' matches at label1:1
status: 1
EOF

# --------------------------------------------------------------
# Checking multiple files at once

check '(logscan --verbose -y abc -y def -n xyz -n zyx one two 2>&1 || echo status: $?) | sort' <<EOF
Pattern 'abc' matches at two:1
Pattern 'def' matches at two:2
Unexpected pattern 'xyz' matches at one:1
status: 1
EOF

check '(logscan --verbose -y abc -y def -n xyz -n zyx -ppos one two 2>&1 || echo status: $?) | sort' <<EOF
Pattern 'abc' matches at two:1
Pattern 'def' matches at two:2
Unexpected pattern 'xyz' matches at one:1
status: 1
EOF


check '(logscan --verbose -y abc -y def -n xyz -n zyx -ppos one two 2>&1 || echo status: $?) | sort' <<EOF
Pattern 'abc' matches at one:4
Pattern 'abc' matches at two:4
Pattern 'def' matches at one:3
Pattern 'def' matches at two:5
EOF

check '(logscan --verbose -y abc -y def -n xyz -n zyx -ppos one two 2>&1 || echo status: $?) | sort' <<EOF
Pattern 'abc' matches at one:7
Pattern 'def' matches at one:6
Unexpected pattern 'zyx' matches at two:7
status: 1
EOF

echo abc >> one
echo def >> two
check 'logscan -y abc -y def -n xyz -n zyx -ppos -t 0.1 one two || echo status: $?' <<EOF
Timeout waiting for patterns to match -- not matched:
one: 'def'
two: 'abc'
status: 1
EOF

# --------------------------------------------------------------
# Waiting for log entries

( sleep 0.1; echo abc; sleep 0.1; echo def ) >> one &

check 'logscan --verbose -y abc -y def -n xyz -n zyx -ppos -t 0.3 one' <<EOF
Pattern 'abc' matches at one:9
Pattern 'def' matches at one:10
EOF

( echo def; echo abc ) >> two

check 'logscan --verbose -y abc -y def -n xyz -n zyx -ppos two' <<EOF
Pattern 'def' matches at two:9
Pattern 'abc' matches at two:10
EOF
